### ISSUE TITLE
Bug in parsing array of boolean

### ISSUE THREAD

**Issue by maartenflippo** [potassco/flatzinc#38]
Consider the following flatzinc statement:

```
array [1..3] of var bool: xs = [x1, x2, x3];
```

The crate fails to parse, seemingly because of the whitespace in the array literal after each comma. I.e. the following does work:

```
array [1..3] of var bool: xs = [x1,x2,x3];
```

We are running version 0.3.20 of the crate. I am happy to submit a PR fixing this if you would be helped by that.

**Comment by sthiele** [comment]
Thank you for reporting the issue. A PR would be very welcome.
